name: build and push

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    # checkout the repository
    - name: checkout repository
      uses: actions/checkout@v1
    
    # setup nuget
    - name: setup nuget
      uses: NuGet/setup-nuget@v1.0.2
    
    # add nuget sources
    - name: add nuget sources
      run: dotnet nuget add source https://nuget.pkg.github.com/josepfranco/index.json -n github -u josepfranco -p ${{ secrets.GH_PACKAGES_TOKEN }} --store-password-in-clear-text
      shell: bash
      
    # build the binaries
    - name: build with dotnet
      run: dotnet build --configuration Release --version-suffix prerelease-$(date +%Y%m%d%H%M%S) -o "./BUILDS/Release/"
      shell: bash
    
    # publish to github packages nuget
    - name: publish to packages
      run: |
           for f in ./BUILDS/Release/*.nupkg
           do
             curl -vX PUT -u "josepfranco:${{ secrets.GH_PACKAGES_TOKEN }}" -F package=@$f https://nuget.pkg.github.com/josepfranco/
           done
      shell: bash
